# node_exporter
node_exporter_version: '1.3.1'

# promtail
promtail_version: '2.6.1'

# go
go_version: '1.20.3'

# cosmovisor
cosmovisor_version: 'v1.0.0'

# Cloudflare API by Nodeist
cloudflare_api_key: ''
