network: bitsong
folder: '.bitsongd'
daemon: bitsongd
chain_id: bitsong-2b
node_version: v0.14.0
repo: https://github.com/bitsongofficial/go-bitsong
genesis: https://raw.githubusercontent.com/bitsongofficial/networks/master/bitsong-2b/genesis.json
seeds: '20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:16056,10de6c207e60b876bdd88571db44d29c18d0cb5d@seed-bitsong.starsquid.io:15605,8defec7d0eec97f507411e02fd2634e3efc997a2@bitsong-seed.panthea.eu:41656'
minimum_gas_price: ''
custom_port_prefix: 160

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 45
wasm: 'inside'
