network: cronos
folder: '.cronos'
daemon: cronosd
chain_id: 'cronosmainnet_25-1'
node_version: 'v1.0.2'
repo: https://github.com/crypto-org-chain/cronos
genesis: 'https://raw.githubusercontent.com/crypto-org-chain/cronos-mainnet/master/cronosmainnet_25-1/genesis.json'
seeds: '0d5cf1394a1cfde28dc8f023567222abc0f47534@cronos-seed-0.crypto.org:26656,3032073adc06d710dd512240281637c1bd0c8a7b@cronos-seed-1.crypto.org:26656,04f43116b4c6c70054d9c2b7485383df5b1ed1da@cronos-seed-2.crypto.org:26656,337377dcda43d79c537d2c4d93ad3b698ce9452e@bd-cronos-mainnet-seed-node-01.bdnodes.net:26656'
custom_port_prefix: 236
update_website_immediately: true
