network: konstellation
folder: '.knstld'
daemon: knstld
chain_id: darchub
node_version: v0.6.2
repo: https://github.com/konstellation/konstellation
genesis: 'https://raw.githubusercontent.com/Konstellation/konstellation/master/config/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:13356'
minimum_gas_price: '0.0001udarc'
custom_port_prefix: 133

# [Optional] Snapshot
snapshot_hour: 3
snapshot_minute: 30
