network: duality
folder: '.duality'
daemon: dualityd
chain_id: duality-testnet-1
node_version: v0.3.4
repo: 'https://github.com/duality-labs/duality'
genesis: 'https://raw.githubusercontent.com/cosmos/testnets/master/replicated-security/duality-testnet-1/duality-testnet-1-genesis.json'
seeds: '2b92aec80bbac6f559a2444b3f14f54b12afcab1@p2p.testnet-1.duality.xyz:26656'
custom_port_prefix: 231

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 0
# wasm: 'outside'
