network: saage
folder: '.sge'
daemon: sged
chain_id: sge-network-3
node_version: v1.0.1
repo: https://github.com/sge-network/sge
genesis: 'https://raw.githubusercontent.com/sge-network/networks/master/sge-network-3/genesis.json'
peers: '4980b478f91de9be0564a547779e5c6cb07eb995@3.239.15.80:26656,0e7042be1b77707aaf0597bb804da90d3a606c08@3.88.40.53:26656'
seeds: '20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:17756'
custom_port_prefix: 177
minimum_gas_price: 0.000usge

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 30
