---
- name: copy tenderduty service file
  become: true
  template:
    src: 'tenderduty.service.j2'
    dest: '/etc/systemd/system/tenderduty.service'
    owner: root
    group: root
    mode: '0644'

- name: copy tenderduty config file
  become: true
  template:
    src: 'config.yml.j2'
    dest: '{{ user_dir }}/tenderduty/config.yml'
    owner: root
    group: root
    mode: '0644'

- name: start tenderduty service
  become: true
  systemd:
    name: 'tenderduty'
    state: restarted
    daemon_reload: yes
    enabled: yes
