---
- name: Clone node repo
  git:
    repo: '{{ repo }}'
    dest: '{{ user_dir }}/{{ network }}'
    version: '{{ node_version }}'
    update: yes
    force: yes
    recursive: no

- name: Install node
  command: '{{ item }}'
  args:
    chdir: '{{ user_dir }}/{{ network }}'
  with_items:
    - 'make install'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'
  when: binary is undefined


- name: download binary
  get_url:
    url: '{{ binary }}'
    dest: '/tmp/binary.tar.gz'
    mode: '0700'
    force: yes

- name: unarchive binary file
  unarchive:
    src: '/tmp/binary.tar.gz'
    dest: '/tmp/'
    mode: '0755'
    remote_src: true

- name: Copy binary
  copy:
    remote_src: true
    src: '/tmp/{{ daemon }}'
    dest: '{{ user_dir }}/go/bin/{{ daemon }}'
    mode: '0755'


- name: Create new directory
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ upgrade_folder }}/bin'
  when: upgrade_folder is defined

- name: copy binary file to cosmovisor upgrade folder
  copy:
    src: '{{ user_dir }}/go/bin/{{ daemon }}'
    dest: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ upgrade_folder }}/bin'
    remote_src: true
    mode: '0755'
  when: upgrade_folder is defined

- name: copy binary file to cosmovisor genesis folder
  copy:
    src: '{{ user_dir }}/go/bin/{{ daemon }}'
    dest: '{{ user_dir }}/{{ folder }}/cosmovisor/genesis/bin'
    remote_src: true
    mode: '0755'
  when: upgrade_folder is not defined

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ network }}d'
    state: restarted
    daemon_reload: yes
    enabled: yes
